# Generated by Django 3.0.6 on 2020-05-17 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEEU_User',
            fields=[
                ('u_id', models.AutoField(db_column='uid', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('clips', models.IntegerField()),
                ('followings', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('sex', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEEU_User_Following',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('following_id', models.ManyToManyField(to='SEEUApp.SEEU_User')),
            ],
        ),
        migrations.CreateModel(
            name='SEEU_User_Followed',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('followed_id', models.ManyToManyField(to='SEEUApp.SEEU_User')),
            ],
        ),
        migrations.CreateModel(
            name='SEEU_Moment',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEEUApp.SEEU_User')),
            ],
        ),
    ]
