# Generated by Django 3.0.6 on 2020-05-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEEUApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Account',
        ),
    ]
