# Generated by Django 3.0.6 on 2020-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEUApp', '0003_auto_20200517_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeu_user',
            name='clips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seeu_user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seeu_user',
            name='followings',
            field=models.IntegerField(default=0),
        ),
    ]
