# Generated by Django 3.0.6 on 2020-05-13 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEUApp', '0006_remove_userprofileinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
